# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

site.title: Random Confounder Theory
description: The antidote is a Randomised Controlled Trial
github_username:
site.author: Joe Cheung

# Email and twitter are optional:
email:
twitter_username: JoeCheung_

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: G-ZWN0CHR9LT

# Everything below here can be ignored, unless you want to change the theme entirely
remote_theme: tufte-pandoc-jekyll

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-pandoc

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge

markdown: Pandoc
pandoc:
  extensions:
    - section-divs
    - from: 'markdown+tex_math_single_backslash'
    - filter: 'pandoc-sidenote'
